function [nucl_names_v,nucl_int_v, six_factors_v, VBUDS_flux_v, VBUDS_e_v, coarse_t_v, fine_t_v, n_act_v, VBUDS_fineflux_v, VBUDS_finee_v]...
       = call_vbuds_c(rx_name,geom,fuel_region,comp,rho,vf,shim,shimconc,...
               actinides,clad_comp,clad_rho,struct_comp,struct_rho,struct_vf,temps,...
               dimen,cell_geom,load_factor,fuel_types,nonfuel_types,ca_types,...
               ca_flag,clad_types,struct_types,mode,x_axis_option,y_axis_option,...
               plot_options,disch_bu,t_res,n_batches,flux_step,burn_step);

    compp=comp'; rhop=rho';vfp=vf'; actinidesp=actinides';
    system('./vbuds');
    load ('variables_after_vbuds.mat');

    %This code always returns 10 output, so if you want 5 output you have
    %to weight the other spots with unused variables