function pL = makelib(ZAIDsToFarm, fineGroupDef)

s0values = 10.^[10 5 3 2 1 0 -1];
pL = struct(...
    'metamat', 'FarmXSMetaHomo4', ...
    'address', pwd, ...
    'verbose', 1, ...
    'explore', 1, ...
'endfversion', 7.1, ...
       'mine', 1, ...
      'plant', 1, ...
  'fertilize', 1, ...
    'harvest', 1, ...
          'e', struct('searchWeb', 0), ...
          'm', struct('downloadTape20s', 1), ...
          'p', struct('MFMTs', [3 1;
                                3 18;
                                3 102;
                                3 251;
                                3 452;
                                ], ...
                        'MFs', [6], ...
                         'Ts', [294], ...
                        'S0s', s0values, ...
                     'IGNstr', '1', ... % read in group structure
                   'groupDef', fineGroupDef, ...
                     'IWTstr', '3'), ... % maybe 7 for fast
           'f', struct('overwriteOutput', 1, ...
                            'logResults', 1), ...
           'h', struct('makeLibrary', 1, ...
                        'makeArrays', 0), ...
                 'ZAIDs',[ZAIDsToFarm 11 1001 8016 11023 92235 92238]);
       %'ZAIDs', [11 1001 8016 40090 92235 92238]);


   end
